pipeline {
    agent any
    
    stages {
        stage ('CHECKOUT') {
            steps {
                sh 'sleep 5'
            }
        }
    
        stage ('BUILD') {
            steps {
                sh 'sleep 5'
            }
        }
        stage ('TEST') {
            steps {
                sh 'sleep 5'
            }
        }
        stage ('DEPLOY') {
            steps {
                sh 'sleep 5'
            }
        }
    }
}